#ifndef PUBNUBHANDLER_GLOBAL_H
#define PUBNUBHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PUBNUBHANDLER_LIBRARY)
#  define PUBNUBHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PUBNUBHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PUBNUBHANDLER_GLOBAL_H
